### ISSUE TITLE
Upload 0.3.2 to jcenter / maven central

### ISSUE THREAD

**Issue by nikos** [domix/spring-boot-starter-jade4j#9]
It would be great to have the version 0.3.1 available via maven central, like described in the project's README file. The latest version available currently in maven central is 0.3.0.
Thanks!

**Comment by domix** [comment]
Thanks for the reminder. In the mean time, spring-boot-starter-jade4j is available in jcenter.
https://bintray.com/domix/spring-boot/spring-boot-starter-jade4j/view

**Comment by nikos** [comment]
Thanks, I will use jcenter with version 0.3.1 in the meantime.
While we are at the topic "releasing" ;-) ... it would be fantastic if you could release the head (may be with integrated #10) to allow fetching your starter pack together with a current jade4j version, what do you think?

**Comment by nikos** [comment]
Thanks for merging in PR #10 
Could you please release this version (0.3.2) to make it available via jcenter / maven central.
Thanks in advance, Niko

**Comment by domix** [comment]
Just releases 0.3.2 to JCenter
